// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserAdmin.Models;

namespace UserAdmin.Migrations
{
    [DbContext(typeof(AdminContext))]
    [Migration("20200602222920_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UserAdmin.Models.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CommentText")
                        .IsRequired();

                    b.Property<int?>("CommenterUserId");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int?>("MessageCommentedMessageID");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("CommentID");

                    b.HasIndex("CommenterUserId");

                    b.HasIndex("MessageCommentedMessageID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("UserAdmin.Models.Message", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("MessageText")
                        .IsRequired();

                    b.Property<int?>("RecipientUserId");

                    b.Property<int?>("SenderUserId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("MessageID");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("UserAdmin.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AdminLevel");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserAdmin.Models.Comment", b =>
                {
                    b.HasOne("UserAdmin.Models.User", "Commenter")
                        .WithMany("UserComments")
                        .HasForeignKey("CommenterUserId");

                    b.HasOne("UserAdmin.Models.Message", "MessageCommented")
                        .WithMany("MessageComments")
                        .HasForeignKey("MessageCommentedMessageID");
                });

            modelBuilder.Entity("UserAdmin.Models.Message", b =>
                {
                    b.HasOne("UserAdmin.Models.User", "Recipient")
                        .WithMany("MessagesReceived")
                        .HasForeignKey("RecipientUserId");

                    b.HasOne("UserAdmin.Models.User", "Sender")
                        .WithMany("MessagesSent")
                        .HasForeignKey("SenderUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
